#!/usr/bin/env bash

# Wrapper executable for casperjs which sets some useful defaults.

usage() {
  echo "Usage: ./runtests [-u http://url] [test to run in tests folder]

Examples:
./runtests >> Runs all tests in tests/ at http://localhost:8180.
./runtests home.js >> Runs home.js tests at http://localhost:8180.
./runtests -u http://www.veoprint.com home.js >> Runs home.js test at http://www.veoprint.com."
  exit 1
}

# Set defaults.
URL='http://localhost:8180'

# Parse options.
while getopts hu: OPTION; do
  case $OPTION in
    h)
      usage
      ;;
    u)
      URL=$OPTARG
      ;;
  esac
done

# Remove the switches we parsed above from the arguments.
shift `expr $OPTIND - 1`

# Now, parse arguments.
TEST=${1-.}

# Remove stored cookies from previous test runs.
rm -f cookies.txt

# Run tests.
echo casperjs --verbose --cookies-file=cookies.txt test tests/$TEST --root=`pwd` --url=$URL
casperjs --verbose --cookies-file=cookies.txt test tests/$TEST --root=`pwd` --url=$URL